# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Headlines' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.6'
    pod 'RxSwift', '~> 4.0'

  # Pods for Headlines

  target 'HeadlinesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeadlinesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
